apiBaseUrl=http://localhost:4111
apiVersion=/api/v1
admin.username=admin
admin.password=admin
uiRemote=http://localhost:4444/wd/hub
uiBaseUrl=http://frontend
uiBrowserSize=1920x1080
uiBrowser=chrome
db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver
db.table.customers=customers
# Fraud service configuration (for testing with WireMock)
fraud.service.url=http://localhost:8089/api/v1/fraud-check