name: Run tests

#триггер
on: [ push, workflow_dispatch ]

jobs:
  run-tests:
    name: Set up(review apps) and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up services
        run: cd infrastructure/docker-compose/ && bash restart-docker.sh && cd ../..

      - name: Wait for services to be ready
          run:|
          echo "Waiting for services to start..."
          # Ожидание пока порт 4111 станет доступен
          timeout 120s bash -c '
          until curl -f -s http://localhost:4111/health > /dev/null; do
          echo "Waiting for server on port 4111..."
          sleep 5
          done
          '
          echo "All services are ready!"

      - name: Run tests
        run: ./mvnw clean test -q